packages:
  - ./*
  - fumadocs/packages/*
  - fumadocs/apps/react-router-18n
  - fumadocs/

autoInstallPeers: false

neverBuiltDependencies: []

overrides:
  unframer: link:../../../.local/share/pnpm/global/5/node_modules/unframer
